FROM python:3.11-slim

WORKDIR /app

# Install libgpiod for low-level access
RUN apt-get update \
 && apt-get install -y --no-install-recommends libgpiod2 \
 && rm -rf /var/lib/apt/lists/*

# Copy & install Python deps (including pigpio now)
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy your app code
COPY . .

EXPOSE 61002
CMD ["python", "app.py"]